spring:
  application:
    name: brotreinos
  # Bloco de configura??o do JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Bloco de configura??o do DataSource (Banco de Dados)
  datasource:
    url: jdbc:mysql://localhost:3306/academia?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  private:
    key-location: classpath:keys/private_key.pem
  public:
    key-location: classpath:keys/public_key.pem